package dev.roland.inventory_management_backend.enums;

public enum DocumentType {
  RFQ,
  SUPPLIER_QUOTATION,
  PURCHASE_ORDER,
  GOODS_RECEIPT,
  CUSTOMER_RFQ,
  SALES_QUOTATION,
  SALES_ORDER,
  DELIVERY_NOTE,
  INVOICE,
  TRANSFER_REQUEST,
  TRANSFER_DELIVERY,
  TRANSFER_RECEIPT,
  STOCK_ADJUSTMENT,
  RETURN
}
