spring:
  application:
    name: inventory-management-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000
#Redis config
redis:
  session:
    ttl-minutes: ${REDIS_SESSION_TTL_MINUTES:8}
#Logging config
logging:
  level:
    org:
      springframework:
        web: DEBUG
      servlet:
        DispatcherServlet: DEBUG
#App config
app:
  security:
    secure-cookie: ${SECURE_HTTP}
#JWT config
security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-time: ${ACCESS_TOKEN_EXPIRY}
    refresh-expiration-time: ${REFRESH_TOKEN_EXPIRY}